# This is a basic workflow to help you get started with ActionsfgfgIDK

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branchhello
  push:
    branches: [ "master", "beta", "alpha", "next" ]


  # Allows you to run this workflow manually from the Actions tab idkffff
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallelgurll
jobs:
  # This workflow contains a single job called "build"dfsfsfd
  build:
    # The type of runner that the job will run onfdfd
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it helffflo how
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Runs a single command using the runners shell
      - name: Run a one-line scripttt22
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install -g @google/semantic-release-replace-plugin
          npm install -g @semantic-release/git
          npm install -g semantic-release
          npx semantic-release --debug
